In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
 data = genfromtxt('bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels = data[:,4]

In [7]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features = data[:,0:4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [13]:
X = features
y = labels

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.33,
                                                    random_state=42)

In [17]:
len(X_train)

919

In [18]:
len(X)

1372

In [19]:
len(X_test)

453

In [21]:
# y_train

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler_object = MinMaxScaler()

In [24]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [25]:
scaled_X_train = scaler_object.transform(X_train)

In [26]:
scaled_X_test = scaler_object.transform(X_test)

In [27]:
scaled_X_train.max()

1.0000000000000002

In [31]:
# scaled_X_train.min()

In [32]:
from keras.models import Sequential
from keras.layers import Dense

In [33]:
model = Sequential()

model.add(Dense(4,
               input_dim=4,
               activation='relu'))

model.add(Dense(8,
               activation='relu'))

model.add(Dense(1,
               activation='sigmoid'))

In [36]:
model.compile(loss='binary_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [38]:
model.fit(scaled_X_train,
         y_train,
         epochs=100,
         verbose=2)

Epoch 1/100
 - 0s - loss: 0.1603 - acc: 0.9587
Epoch 2/100
 - 0s - loss: 0.1546 - acc: 0.9608
Epoch 3/100
 - 0s - loss: 0.1491 - acc: 0.9630
Epoch 4/100
 - 0s - loss: 0.1440 - acc: 0.9630
Epoch 5/100
 - 0s - loss: 0.1387 - acc: 0.9630
Epoch 6/100
 - 0s - loss: 0.1344 - acc: 0.9619
Epoch 7/100
 - 0s - loss: 0.1300 - acc: 0.9674
Epoch 8/100
 - 0s - loss: 0.1254 - acc: 0.9684
Epoch 9/100
 - 0s - loss: 0.1210 - acc: 0.9706
Epoch 10/100
 - 0s - loss: 0.1183 - acc: 0.9717
Epoch 11/100
 - 0s - loss: 0.1143 - acc: 0.9717
Epoch 12/100
 - 0s - loss: 0.1107 - acc: 0.9695
Epoch 13/100
 - 0s - loss: 0.1073 - acc: 0.9717
Epoch 14/100
 - 0s - loss: 0.1036 - acc: 0.9728
Epoch 15/100
 - 0s - loss: 0.1008 - acc: 0.9739
Epoch 16/100
 - 0s - loss: 0.0979 - acc: 0.9739
Epoch 17/100
 - 0s - loss: 0.0958 - acc: 0.9750
Epoch 18/100
 - 0s - loss: 0.0932 - acc: 0.9739
Epoch 19/100
 - 0s - loss: 0.0901 - acc: 0.9782
Epoch 20/100
 - 0s - loss: 0.0882 - acc: 0.9782
Epoch 21/100
 - 0s - loss: 0.0860 - acc: 0.9771
E

In [40]:
# model.predict_classes(scaled_X_test)

In [41]:
model.metrics_names

['loss', 'acc']

In [42]:
from sklearn.metrics import confusion_matrix,classification_report

In [43]:
predictions = model.predict_classes(scaled_X_test)

In [44]:
confusion_matrix(y_test,predictions)

array([[256,   1],
       [  0, 196]])

In [45]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       257
        1.0       0.99      1.00      1.00       196

avg / total       1.00      1.00      1.00       453



In [46]:
model.save('feelsModel.h5')

In [47]:
from keras.models import load_model

In [48]:
new_model = load_model('feelsModel.h5')

In [49]:
new_model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    